# Generated by Django 5.1.7 on 2025-04-19 14:59

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='DEFAULT_ID', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='whatsapp',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
