# Generated by Django 5.1.7 on 2025-04-19 15:07

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_patient_patient_id_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='DEFAULT_ID', editable=False, max_length=10, unique=True),
        ),
    ]
