# Generated by Django 5.1.7 on 2025-04-20 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_patient_patient_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
