# Generated by Django 5.1.7 on 2025-04-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='sms_status',
            field=models.CharField(default='not sent', max_length=20),
        ),
    ]
