# Generated by Django 5.1.7 on 2025-04-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_diagnosis_medicalhistory_procedure_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='toothstatus',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='ToothStatus',
        ),
    ]
