# Generated by Django 5.1.7 on 2025-04-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_diagnosis_procedure_toothstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='toothstatus',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='ToothStatus',
        ),
    ]
