# Generated by Django 5.1.7 on 2025-04-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_allergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('missing', 'Missing'), ('impacted', 'Impacted'), ('diagnosis', 'Diagnosis'), ('procedure', 'Procedure')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_chart', to='home.patient')),
            ],
        ),
    ]
