# Generated by Django 5.1.7 on 2025-04-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_dentalchart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalchart',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='DentalChart',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
