# Generated by Django 5.1.7 on 2025-04-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_toothstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToothStatus',
        ),
    ]
