# Generated by Django 5.1.7 on 2025-04-26 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_delete_toothstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToothStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('missing', 'Missing'), ('impacted', 'Impacted')], default='normal', max_length=10)),
                ('tooth_type', models.CharField(choices=[('permanent', 'Permanent'), ('deciduous', 'Deciduous')], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='home.patient')),
            ],
        ),
    ]
