# Generated by Django 5.1.7 on 2025-04-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_delete_toothstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('permanent', 'Permanent'), ('deciduous', 'Deciduous')], max_length=20)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('missing', 'Missing'), ('impacted', 'Impacted')], default='normal', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
            options={
                'unique_together': {('patient', 'number', 'type')},
            },
        ),
    ]
