# Generated by Django 5.1.7 on 2025-04-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_tooth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeethStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.IntegerField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('missing', 'Missing'), ('impacted', 'Impacted')], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Tooth',
        ),
    ]
