# Generated by Django 5.1.7 on 2025-04-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_teethstatus_delete_tooth'),
    ]

    operations = [
        migrations.AddField(
            model_name='teethstatus',
            name='is_deciduous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teethstatus',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('missing', 'Missing'), ('impacted', 'Impacted')], max_length=20),
        ),
    ]
