# Generated by Django 5.1.7 on 2025-04-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_teethstatus_is_deciduous_alter_teethstatus_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeethStatus',
        ),
    ]
