# Generated by Django 5.1.7 on 2025-04-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_delete_teethstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_teeth', models.JSONField(default=dict)),
                ('deciduous_teeth', models.JSONField(default=dict)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
    ]
