# Generated by Django 5.1.7 on 2025-04-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_dentalchart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DentalChart',
        ),
    ]
