# Generated by Django 5.1.7 on 2025-04-26 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_deciduoustooth_permanenttooth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permanenttooth',
            name='patient',
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('diagnosis', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('teeth', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='DeciduousTooth',
        ),
        migrations.DeleteModel(
            name='PermanentTooth',
        ),
    ]
