# Generated by Django 5.1.7 on 2025-04-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_permanenttooth_patient_diagnosis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
