# Generated by Django 5.1.7 on 2025-04-26 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.doctor'),
        ),
    ]
