# Generated by Django 5.1.7 on 2025-04-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_diagnosis_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
