# Generated by Django 5.1.7 on 2025-04-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_diagnosis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
