# Generated by Django 5.1.7 on 2025-04-27 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_diagnosis_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.doctor'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='teeth',
            field=models.CharField(max_length=10),
        ),
    ]
