# Generated by Django 5.1.7 on 2025-04-27 03:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_diagnosis_doctor_alter_diagnosis_teeth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='teeth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
