# Generated by Django 5.1.7 on 2025-04-27 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_diagnosis_date_alter_diagnosis_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
