# Generated by Django 5.1.7 on 2025-04-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_diagnosis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
