# Generated by Django 5.1.7 on 2025-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-27 07:46:00'),
            preserve_default=False,
        ),
    ]
