# Generated by Django 5.1.7 on 2025-04-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_diagnosis_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientXRay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patient_xrays/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrays', to='home.patient')),
            ],
        ),
    ]
