# Generated by Django 5.1.7 on 2025-04-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_patientxray'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('form', models.CharField(choices=[('gel', 'Gel'), ('pill', 'Pill'), ('tablet', 'Tablet'), ('lotion', 'Lotion')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='home.patient')),
            ],
        ),
    ]
