# Generated by Django 5.1.7 on 2025-04-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_laborder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabOrder',
        ),
    ]
