# Generated by Django 5.1.7 on 2025-04-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_insurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insurance',
        ),
    ]
