# Generated by Django 5.1.7 on 2025-04-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
