# Generated by Django 5.1.7 on 2025-04-30 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.diagnosis')),
            ],
        ),
    ]
