# Generated by Django 5.1.7 on 2025-04-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
