# Generated by Django 5.1.7 on 2025-05-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
