# Generated by Django 5.1.7 on 2025-05-01 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.treatment')),
            ],
        ),
    ]
