# Generated by Django 5.1.7 on 2025-05-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_data', models.JSONField(default=list)),
                ('deciduous_data', models.JSONField(default=list)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
    ]
