# Generated by Django 5.1.7 on 2025-05-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_dentalchart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='sms_status',
        ),
    ]
