# Generated by Django 5.1.7 on 2025-05-20 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_remove_appointment_sms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='teeth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.treatment'),
        ),
    ]
