# Generated by Django 5.1.7 on 2025-05-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_remove_laborder_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insurance',
        ),
    ]
